name: Install and Run Tosca CLI

on: [push]

jobs:
  run-tosca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files in the current directory
        run: ls
        

      - name: Install Tosca Execution Client
        run: |
          #Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          .\tosca_execution_client.sh
      # - name: Run Tosca Tests
      #   run: |
          # Replace with your actual parameters
          # $toscaServerUrl = "<your_tosca_server_url>"
          # $projectName = "<your_project_name>"
          # $eventName = "<your_event_name>"
          
          # Execute the Tosca CLI command
          #./tosca_execution_client.sh --toscaServerUrl <toscaServerUrl> --projectName <projectName> --events <events> [Options]
